language: c

env:
  global:
    - TMPDIR=/tmp

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - bubblewrap
    - os: osx
      osx_image: xcode11
      addons:
        homebrew:
          update: true

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

script:
  - asdf plugin-test ocaml $TRAVIS_BUILD_DIR --asdf-tool-version 4.08.1
